spring:
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
    com.mungta.accusation: debug
