server:
  port: 8089
---
springdoc:
  swagger-ui:
    operationsSorter: method

spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxx@gmail.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
  cloud:
    stream:
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        producer-out-0:
          destination: accusation-topic
          contentType: application/json

api:
  url:
    user: http://localhost:8081/mungta/users
    party: http://localhost:8082/mungta/parties

---
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          producer-out-0:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        producer-out-0:
          destination: accusation-topic
          contentType: application/json

api:
  url:
    user: http://gateway:8080
    party: http://gateway:8080
